<?php


$category = array_reduce( Su_Tools::get_category(), function ( $id, $category ) {
    $id[$category->id] = $category->title; return $id; }, [ ] );

$k2_category = array_reduce( Su_Tools::get_k2_category(), function ( $id, $category ) {
    $id[$category->id] = $category->title; return $id; }, [ ] );

  return [
    "name"         => "Portfolio",
    "slug"         => "bdt_portfolio",
    "groups"       => ["Shortcode Ultimate", "content"],
    "form"         => [
      "general"      => [
        [ 
          "name"        => "source_type",
          "type"        => "select",
          "label"       => "Source Type",
          "options"     => [
            "category"    => "Joomla Category",
            "k2-category" => "K2 Category",
          ],
        ],
        [ 
          "name"        => "j_category",
          "type"        => "select",
          "label"       => "Select Category",
          "multiple"    => true,
          "depends"     => [
            "source_type" => "category",
          ],
          "options"     => $category,
        ],
        [ 
          "name"        => "k2_category",
          "type"        => "select",
          "label"       => "Select Category",
          "depends"     => [
            "source_type" => "k2-category",
          ],
          "multiple"    => true,
          "options"     => $k2_category,
        ],
        [
          "name"         => "layout",
          "type"         => "select",
          "options"      => [
            "grid"         => "Grid",
            "masonry"      => "Masonry",
            "slider"       => "Slider",
          ],
          "value"        => "grid",
        ],
        [
          "name"         => "limit",
          "help"         => "Maximum number of item that you want to display.",
          "type"         => "slider",
          "min"          => "5",
          "max"          => "100",
          "value"        => "12",
        ],
        [
          "name"         => "show_more",
          "help"         => "You can set show more button by clicking yes.",
          "label"        => "Show More Button",
          "type"         => "switch",
        ],
        [
          "name"         => "show_more_item",
          "help"         => "How many item you want to display by clicking show more button?",
          "label"        => "Show More Limit",
          "type"         => "slider",
          "min"          => "1",
          "max"          => "12",
          "value"        => "4",
        ],
        [
          "name"         => "show_more_action",
          "help"         => "How you want work the show more button.",
          "label"        => "Show More Action",
          "type"         => "select",
          "options"      => [
            "click"        => "Click",
            "auto"         => "Auto",
          ],
          "value"        => "click",
        ],
        [
          "name"         => "order",
          "type"         => "select",
          "options"      => [
            "created"      => "Created Date",
            "title"        => "Title",
            "hits"         => "Hits",
            "ordering"     => "Ordering",
          ],
          "value"        => "created",
        ],
        [
          "name"         => "order_by",
          "label"        => "Order Type",
          "type"         => "select",
          "options"      => [
            "asc"          => "Ascending",
            "desc"         => "Decending",
          ],
          "value"        => "desc",
        ],
        [
          "name"         => "horizontal_gap",
          "label"        => "Horizontal Gap",
          "type"         => "slider",
          "max"          => "50",
          "step"         => "5",
          "value"        => "10",
        ],
        [
          "name"         => "vertical_gap",
          "label"        => "Vertical Gap",
          "type"         => "slider",
          "max"          => "50",
          "step"         => "5",
          "value"        => "10",
        ],
        [
          "name"         => "thumb_resize",
          "help"         => "If you select yes then the image will be croped.",
          "label"        => "Thumb Resize",
          "type"         => "switch",
          "value"        => true,
        ],
        [
          "name"         => "filter",
          "help"         => "You can set your filter show/hide from here.",
          "type"         => "switch",
          "value"        => true,
        ],
        [
          "name"         => "filter_deeplink",
          "label"        => "Filter Deep Link",
          "type"         => "switch",
        ],
        [
          "name"         => "show_link",
          "label"        => "Show Link",
          "type"         => "switch",
          "value"        => true,
        ],
        [
          "name"         => "show_zoom",
          "label"        => "Show Zoom",
          "type"         => "switch",
          "value"        => true,
        ],
        [
          "name"         => "include_article_image",
          "label"        => "Include Article Image",
          "type"         => "switch",
        ],
      ],

      "styles"       => [
        [
          "name"         => "style",
          "type"         => "select",
          "options"      => [
            "1"            => "Style 1",
            "2"            => "Style 2",
            "3"            => "Style 3",
            "4"            => "Style 4",
            "5"            => "Style 5",
            "6"            => "Style 6",
            "7"            => "Style 7",
            "8"            => "Style 8",
            "9"            => "Style 9",
            "10"           => "Style 10",
          ],
          "value"        => "1",
        ],
        [
          "name"         => "loading_animation",
          "label"        => "Loading Animation",
          "type"         => "select",
          "options"      => [
            "default"      => "Default",
            "fadeIn"       => "Fade In",
            "lazyLoading"  => "LazyLoading",
            "fadeInToTop"  => "Fade In To Top",
            "sequentially" => "Sequentially",
            "bottomToTop"  => "Bottom To Top",
          ],
          "value"        => "default",
        ],
        [
          "name"         => "filter_animation",
          "label"        => "Filter Animation",
          "type"         => "select",
          "options"      => [
            "fadeOut"      => "Fade Out",
            "quicksand"    => "Quicksand",
            "boxShadow"    => "Box Shadow",
            "bounceLeft"   => "Bounce Left",
            "bounceTop"    => "Bounce Top",
            "bounceBottom" => "Bounce Bottom",
            "moveLeft"     => "Move Left",
            "slideLeft"    => "Slide Left",
            "fadeOutTop"   => "Fade Out Top",
            "sequentially" => "Sequentially",
            "skew"         => "Skew",
            "slideDelay"   => "Slide Delay",
            "3dflip"       => "3d Flip",
            "rotateSides"  => "Rotate Sides",
            "flipOutDelay" => "Flip Out Delay",
            "flipOut"      => "Flip Out",
            "unfold"       => "Unfold",
            "foldLeft"     => "Fold Left",
            "scaleDown"    => "Scale Down",
            "scaleSides"   => "Scale Sides",
            "frontRow"     => "Front Row",
            "flipBottom"   => "Flip Bottom",
            "rotateRoom"   => "Rotate Room",
          ],
          "value"        => "rotateSides",
        ],
        [
          "name"         => "filter_style",
          "label"        => "Filter Style",
          "type"         => "select",
          "options"      => [
            "1"            => "Style 1",
            "2"            => "Style 2",
            "3"            => "Style 3",
            "4"            => "Style 4",
            "5"            => "Style 5",
            "6"            => "Style 6",
            "7"            => "Style 7",
            "8"            => "Style 8",
            "9"            => "Style 9",
          ],
          "value"        => "1",
        ],
        [
          "name"         => "filter_align",
          "label"        => "Filter Align",
          "type"         => "select",
          "options"      => [
            "center"       => "Center",
            "left"         => "Left",
            "right"        => "Right",
          ],
          "value"        => "center",
        ],
      ],
      "responsive" => [
        [
          "name"         => "large",
          "help"         => "Which item you need to show your large device on responsive mode.",
          "label"        => "Large Device Item",
          "type"         => "slider",
          "min"          => "1",
          "max"          => "10",
          "value"        => "4",
        ],
        [
          "name"         => "medium",
          "help"         => "Which item you need to show your medium device on responsive mode.",
          "label"        => "Medium Device Item",
          "type"         => "slider",
          "min"          => "1",
          "max"          => "5",
          "value"        => "3",
        ],
        [
          "name"         => "small",
          "help"         => "Which item you need to show your small device on responsive mode.",
          "label"        => "Small Device Item",
          "type"         => "slider",
          "min"          => "1",
          "max"          => "5",
          "value"        => "1",
        ],
      ],

      "Animation" => [
        [
          "name"                => "animation",
          "label"               => "Page Loading Animation",
          "type"                => "select",
          "options"             => [
            "fadeInLeft"  => "Left To Right",
            "fadeInRight" => "Right To Left",
            "fadeInUp"    => "Bottom To Top",
            "fadeInDown"  => "Top To Bottom",
            "fadeIn"      => "Fade In",
            "zoomIn"      => "Zoom In",
            0             => "No Animation",
          ],
          "value"               => "fadeIn",
        ],
      ],
    ],
  ];